
PRE_POUND= pre\#
POUND_SIGN= $(PRE_POUND:pre\%=%)

ROGER= up.and.down
STEPHEN= $(ROGER:%.down=%.up)

awesome := OUTPUT += General electric! $(STUFF)
awesome := ROGER= ROGER
awesome: thrust
	echo "$(ROGER)"
	echo "$(STEPHEN)"
	echo "$(OUTPUT)"


OUTPUT=not via awesome!
STUFF=and so on
AL=al
thrust:fin$(AL)
	echo "$(ROGER)"
	echo "$(STEPHEN)"
	echo "$(OUTPUT)"


final:
	echo "final!"

